// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/chencheng8888/GoDo/api"
	"github.com/chencheng8888/GoDo/config"
	"github.com/chencheng8888/GoDo/controller"
	"github.com/chencheng8888/GoDo/dao"
	"github.com/chencheng8888/GoDo/log"
	"github.com/chencheng8888/GoDo/scheduler"
)

// Injectors from wire.go:

func WireNewApp(configConfig *config.Config) (*App, error) {
	serverConfig := config.GetServerConfig(configConfig)
	scheduleConfig := config.GetScheduleConfig(configConfig)
	logConfig := config.GetLogConfig(configConfig)
	sugaredLogger, err := log.NewZapSugaredLogger(logConfig)
	if err != nil {
		return nil, err
	}
	logMiddleware := scheduler.NewLogMiddleware(sugaredLogger)
	dbConfig := config.GetDBConfig(configConfig)
	db, err := dao.NewDB(dbConfig, sugaredLogger)
	if err != nil {
		return nil, err
	}
	taskLogDao := dao.NewTaskLogDao(db)
	taskLogMiddleware := scheduler.NewTaskLogMiddleware(sugaredLogger, taskLogDao)
	schedulerScheduler := scheduler.NewScheduler(scheduleConfig, logMiddleware, taskLogMiddleware, sugaredLogger)
	taskController := controller.NewTaskController(schedulerScheduler, scheduleConfig)
	engine := api.NewGinEngine(taskController)
	apiAPI := api.NewAPI(serverConfig, engine, sugaredLogger)
	app := NewApp(apiAPI, schedulerScheduler)
	return app, nil
}
