// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/chencheng8888/GoDo/api"
	"github.com/chencheng8888/GoDo/config"
	"github.com/chencheng8888/GoDo/controller"
	"github.com/chencheng8888/GoDo/dao"
	"github.com/chencheng8888/GoDo/pkg/id_generator"
	"github.com/chencheng8888/GoDo/pkg/log"
	"github.com/chencheng8888/GoDo/scheduler"
	"github.com/chencheng8888/GoDo/scheduler/domain"
	"github.com/chencheng8888/GoDo/scheduler/implement"
)

import (
	_ "github.com/chencheng8888/GoDo/docs"
)

// Injectors from wire.go:

func WireNewApp(configConfig *config.Config) (*App, error) {
	serverConfig := config.GetServerConfig(configConfig)
	scheduleConfig := config.GetScheduleConfig(configConfig)
	logConfig := config.GetLogConfig(configConfig)
	sugaredLogger, err := log.NewZapSugaredLogger(logConfig)
	if err != nil {
		return nil, err
	}
	logMiddleware := domain.NewLogMiddleware(sugaredLogger)
	dbConfig := config.GetDBConfig(configConfig)
	db, err := dao.NewDB(dbConfig, sugaredLogger)
	if err != nil {
		return nil, err
	}
	taskLogDao := dao.NewTaskLogDao(db)
	taskLogMiddleware := domain.NewTaskLogMiddleware(sugaredLogger, taskLogDao)
	taskInfoDao := dao.NewTaskInfoDao(db)
	cronScheduler, err := implement.NewCronScheduler(scheduleConfig, logMiddleware, taskLogMiddleware, taskInfoDao, sugaredLogger)
	if err != nil {
		return nil, err
	}
	schedulerScheduler := scheduler.NewScheduler(cronScheduler)
	taskIDGenerator := id_generator.NewTaskIDGenerator()
	taskController, err := controller.NewTaskController(schedulerScheduler, taskIDGenerator, scheduleConfig)
	if err != nil {
		return nil, err
	}
	engine := api.NewGinEngine(taskController, sugaredLogger)
	apiAPI := api.NewAPI(serverConfig, engine, sugaredLogger)
	app := NewApp(apiAPI, schedulerScheduler)
	return app, nil
}
