// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "鉴权"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/controller.LoginResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "login failed",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "sign token failed",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks/add_shell_task": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建一个新的Shell任务，支持定时执行，任务所有者从JWT token中获取",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理"
                ],
                "summary": "添加Shell任务",
                "parameters": [
                    {
                        "description": "任务创建参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.AddShellTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/controller.AddShellTaskResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request: invalid request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: your request may be unauthorized; Authorization header required; Authorization header must be Bearer \u003ctoken\u003e; Invalid or expired token",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks/delete": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据任务ID和JWT token中的用户名删除指定任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理"
                ],
                "summary": "删除任务",
                "parameters": [
                    {
                        "description": "删除任务参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.DeleteTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Authorization header required / Authorization header format must be Bearer \u003ctoken\u003e / Invalid or expired token",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "删除任务失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks/delete_file": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除对应的文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理"
                ],
                "summary": "删除对应的文件",
                "parameters": [
                    {
                        "description": "文件删除参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.DeleteFileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request: invalid request; file not found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: your request may be unauthorized; Authorization header required; Authorization header format must be Bearer \u003ctoken\u003e; Invalid or expired token; your user account may have been deleted",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: delete file failed",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据 JWT token 中的用户名获取该用户的所有任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理"
                ],
                "summary": "获取用户任务列表",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/controller.ListTaskResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized:",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks/list_files": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查询已有文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理"
                ],
                "summary": "查询已有文件",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/controller.ListFilesResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized: your request may be unauthorized; Authorization header required; Authorization header must be Bearer \u003ctoken\u003e; Invalid or expired token",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: search failed",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks/upload_file": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "上传文件到服务器，用于后续任务执行",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理"
                ],
                "summary": "上传文件",
                "parameters": [
                    {
                        "type": "file",
                        "description": "文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/controller.UploadScriptResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request: file not uploaded; file too large; file number limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: Authorization header required; wrong format (must be Bearer \u003ctoken\u003e); invalid or expired token; your request may be unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Server Error: file save failed; search failed",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.AddShellTaskRequest": {
            "description": "添加Shell任务的请求参数",
            "type": "object",
            "required": [
                "command",
                "description",
                "scheduled_time",
                "task_name",
                "timeout"
            ],
            "properties": {
                "args": {
                    "description": "命令参数",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "--full"
                    ]
                },
                "command": {
                    "description": "执行命令",
                    "type": "string",
                    "example": "./backup.sh"
                },
                "description": {
                    "description": "任务描述",
                    "type": "string",
                    "example": "每日数据备份任务"
                },
                "scheduled_time": {
                    "description": "Cron表达式(支持秒级)",
                    "type": "string",
                    "example": "0 2 * * * *"
                },
                "task_name": {
                    "description": "任务名称",
                    "type": "string",
                    "example": "daily-backup"
                },
                "timeout": {
                    "description": "超时时间(秒)，最大2小时",
                    "type": "integer",
                    "maximum": 7200,
                    "example": 1800
                },
                "use_shell": {
                    "description": "是否使用Shell",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "controller.AddShellTaskResponseData": {
            "description": "添加任务成功响应数据",
            "type": "object",
            "properties": {
                "task_id": {
                    "description": "新创建的任务ID",
                    "type": "string",
                    "example": "12345"
                }
            }
        },
        "controller.DeleteFileRequest": {
            "type": "object",
            "properties": {
                "file_name": {
                    "description": "文件名",
                    "type": "string",
                    "example": "1699123456789-script.sh"
                }
            }
        },
        "controller.DeleteTaskRequest": {
            "description": "删除任务的请求参数",
            "type": "object",
            "required": [
                "task_id",
                "user_name"
            ],
            "properties": {
                "task_id": {
                    "description": "任务ID",
                    "type": "string",
                    "example": "12345"
                },
                "user_name": {
                    "description": "任务拥有者",
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "controller.ListFilesResponseData": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "controller.ListTaskResponseData": {
            "description": "任务列表响应数据结构",
            "type": "object",
            "properties": {
                "tasks": {
                    "description": "任务列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.TaskResponse"
                    }
                }
            }
        },
        "controller.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "controller.LoginResponseData": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "controller.TaskResponse": {
            "description": "任务信息响应结构",
            "type": "object",
            "properties": {
                "description": {
                    "description": "任务描述",
                    "type": "string",
                    "example": "每日数据备份任务"
                },
                "id": {
                    "description": "任务ID",
                    "type": "string",
                    "example": "12345"
                },
                "job": {
                    "description": "任务详情(JSON格式)",
                    "type": "string",
                    "example": "{\"command\":\"/bin/bash\",\"args\":[\"backup.sh\"]}"
                },
                "job_type": {
                    "description": "任务类型",
                    "type": "string",
                    "example": "shell"
                },
                "owner_name": {
                    "description": "任务拥有者",
                    "type": "string",
                    "example": "admin"
                },
                "scheduled_time": {
                    "description": "Cron表达式",
                    "type": "string",
                    "example": "0 2 * * * *"
                },
                "task_name": {
                    "description": "任务名称",
                    "type": "string",
                    "example": "daily-backup"
                }
            }
        },
        "controller.UploadScriptResponseData": {
            "description": "脚本上传成功响应数据",
            "type": "object",
            "properties": {
                "file_name": {
                    "description": "上传后的文件名",
                    "type": "string",
                    "example": "1699123456789-script.sh"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "GoDo任务调度系统API",
	Description:      "这是一个基于Go语言开发的任务调度系统API文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
